title: Keep Your Options Open.
tagline: "A running ledger of learning investment and gardening, Mountain and Sea Foundation's program on financial literacy for growers."
description: A learning journey about investment options.
url: "https://www.keepyouroptions.com"
baseurl: ""

feed:
  icon: /assets/favicon/android-chrome-512x512.png

markdown: kramdown
permalink: /:year/:month/:title.html

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

show_excerpts: true
